### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by stephenl03** [secdevops-cuse/CyberRange#75]
`make` will fail because of this line. The four spaces need to be a `<tab>`. If a PR is needed, I can submit one...

https://github.com/secdevops-cuse/CyberRange/blob/aa7cfe28ae9f31dbe1a4ee929637ef178224a52e/Makefile#L169

**Comment by gstb989** [comment]
I ran into this as well, simple fix but I tend to forget I did that originally.

**Comment by cappetta** [comment]
Apologies for not engaging, for some reason I just saw this.  I assump this is fixed by now as I've definitely pushed a bunch of changes since Feb.    

Side note - Yes make, like YAML, is very sensitive to spaces / tabs.  I've got the CICD Pipeline performing make / terraform / inspec check plus a bunch of other changes in my current PR - just working through a few more things.  Closing this out.
